TARGET                 = uilli
ARDUINO_LIBS           = Servo
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE     = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf 
 include /usr/share/arduino/Arduino.mk
